### PR TITLE
Update cargo-vet settings

### PR DESCRIPTION
**Pull request by jeffcharles**
Let me know if you're not comfortable with marking our packages as audited.

### CODE REVIEW

**Review by saulecabrera — APPROVED** [review]

**Comment by saulecabrera** [comment]
> Let me know if you're not comfortable with marking our packages as audited.

All this looks reasonable to me!

**Comment by jeffcharles** [comment]
I'm actually realizing `audit-as-crates-io` should probably be set to `false` because vetting will break as soon as a version change happens

**Comment by jeffcharles** [comment]
For context, I read through https://mozilla.github.io/cargo-vet/first-party-code.html. My understanding is that `audit-as-crates-io` exists to handle cases where your patching a third-party crate in your project and should be set to `true` when the crate contains third-party code. I don't think that applies in our case so it should be set to `false`. Though we can still release audits for our own crates of course.

**Comment by saulecabrera** [comment]
Good catch, reading through the description that is my understanding as well, I still have some open questions, but I don't think we need to block this PR on those, and perhaps we can take them offline.

**Review by saulecabrera — APPROVED** [review]

**Pull request merged**
